image:
  repository: devopsyusuf/complete-devops-project
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port:8080
ingress :
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false  